### ISSUE TITLE
Access denied after unable to copy to clipboard

### ISSUE THREAD

**Issue by LordUber** [extesy/DeckTracker#216] opened 2018-05-14 13:54 UTC
I had an issue where I could not copy to the clipboard (after working an impot once successfully). Then after a reinstall, I got an access violation. Another reinstall x2 still has this problem, Any ideas? Is a fix required?

Windows 10, zonealarm AV

**Comment by extesy** [comment] 2018-05-14 21:23
Duplicate of #129

**Closed as completed by extesy** 2018-05-14 21:23 UTC

**Comment by LordUber** [comment] 2018-05-15 01:47
The problem was my antivirus and firewall, Zonealarm. Disabling it temporarily fixed the problem.

**Comment by extesy** [comment] 2018-05-15 17:00
Thanks for the follow up. Unfortunately it's impossible to detect which application blocks the keyboard from the deck tracker.
