### ISSUE TITLE
Tracker will not populate for me

### ISSUE THREAD

**Issue by Timshady79** [extesy/DeckTracker#107] opened 2017-08-05 14:45 UTC
I am opening the tracker before opening TESL however the tracker remains blank.  I cannot get my collection or decks to populate in the tracker.  Am i missing a step somewhere?  I downloaded it for the first time last night shortly after the latest release.  Today I uninstalled it and downloaded the previous release but had the same issue.  I've tried playing ranked, arena and practice battles with the tracker open (after opening it before the game) but it remains blank for me.  any assistance you could provide would be greatly appreciated.  Thank you for your time.  

-Tim

**Comment by netlag666** [comment] 2017-08-05 18:53
Snap! Exactly the same scenario. I've tried every combination I can think of. I run with admin rights, run before the game starts... nothing... It picks up that the game is running, writing goes blue then eventually red and all the buttons are greyed out with no data at all.

**Comment by extesy** [comment] 2017-08-05 19:20
This is a known issue, duplicate of #5. Please try the solution from that ticket (the link is closer to the end).

**Closed by extesy** 2017-08-05 19:20 UTC
