### ISSUE TITLE
TES:L Detection of Deck Archetype not working

### ISSUE THREAD

**Issue by andyPetsch** [extesy/DeckTracker#211] opened 2018-04-25 12:16 UTC
Feature not working as expected:  Detection of opponents deck archetype

The expansion "Houses of Morrowind" did introduce three-colored decks. So far, UDT only shows two-colored archetypes (e.g. sorcerer, archer)

**Comment by extesy** [comment] 2018-04-26 11:47
Duplicate of #210

**Closed as completed by extesy** 2018-04-26 11:47 UTC
