### ISSUE TITLE
Where is the source code for DeckTracker.InGame.dll?

### ISSUE THREAD

**Issue by AndrewSav** [extesy/DeckTracker#146] opened 2017-10-26 08:55 UTC
Hey, is the source code in this repo incomplete? I cannot find sources for DeckTracker.InGame.dll and without it the app does not seem to want to run when compiling from sources.

Also not sure if you realize this or not, but you have the password for you pfx file in your DeckTracker.csproj  Not a big deal, since you are not publishing the pfx, yet, something you might want to be aware of.

**Comment by extesy** [comment] 2017-10-26 20:08
Duplicate of #131

**Closed by extesy** 2017-10-26 20:08 UTC
