### ISSUE TITLE
[BUG] [PERFORMANCE] Repeatable error after long time in game

### ISSUE THREAD

**Issue by VitaliyKulikov** [extesy/DeckTracker#97] opened 2017-07-27 05:57 UTC
After 2-3 hours game provide strange game issues, like:
* missed/empty text on cards
* card's text fully replaced by byte-code
* freezes on cards draw or play

Here is `error.log`
> NOTE: Seems need time stamp to provide correct log
``` c#
dwd.core.sqlite.SQLiteException: Unable to bind parameter c6758770-9b9d-11e6-9f33-a24fc0d9649c-title at 2. SQLite Error Misuse
  at dwd.core.sqlite.SimpleSQLiteCommand.BindParameter (IntPtr stmt, Int32 index, System.String value) [0x00000] in <filename unknown>:0 
  at dwd.core.sqlite.SimpleSQLiteCommand.AddArgument (System.String arg) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.TryLocalize (System.String key, System.String& value, System.Object[] args) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.Localize (System.String key, System.Object[] args) [0x00000] in <filename unknown>:0 
  at L.LT (System.String key) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.get_DisplayText () [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.ToString () [0x00000] in <filename unknown>:0 
  at DeckTracker.Messages.MessageDispatcher.OnClientCommand (Int32 id, CommandType command, System.String parameter) [0x00000] in <filename unknown>:0 
Unprocessable message: {"name":"SequenceMessage","value":{"msg":{"name":"EntityDestroyed","value":{"gameID":"6d5ac340-727e-11e7-a0e7-0663a300f29f","entityID":"6dd3ba82-7683-0a1d-45d6-453c388a1092"}}}}
Error while processing dwd.core.match.sequence.messages.SequenceMessage: System.NullReferenceException: Object reference not set to an instance of an object
  at DeckTracker.Messages.DireWolfDigital.SequenceMessageHandler.EntityDestroyed (System.Object message) [0x00000] in <filename unknown>:0 
  at DeckTracker.Messages.DireWolfDigital.SequenceMessageHandler.Handle (System.Object baseMessage) [0x00000] in <filename unknown>:0 
  at DeckTracker.Messages.MessageDispatcher.OnMessage (System.Object message, MessageType type) [0x00000] in <filename unknown>:0 
Unprocessable message: {"name":"SequenceMessage","value":{"msg":{"name":"EntityDestroyed","value":{"gameID":"6d5ac340-727e-11e7-a0e7-0663a300f29f","entityID":"455adb58-6b19-c059-3ca9-12bd4d50407f"}}}}
Error while processing dwd.core.match.sequence.messages.SequenceMessage: System.NullReferenceException: Object reference not set to an instance of an object
  at DeckTracker.Messages.DireWolfDigital.SequenceMessageHandler.EntityDestroyed (System.Object message) [0x00000] in <filename unknown>:0 
  at DeckTracker.Messages.DireWolfDigital.SequenceMessageHandler.Handle (System.Object baseMessage) [0x00000] in <filename unknown>:0 
  at DeckTracker.Messages.MessageDispatcher.OnMessage (System.Object message, MessageType type) [0x00000] in <filename unknown>:0 
dwd.core.sqlite.SQLiteException: Unable to bind parameter com.direwolfdigital.hydra.rules.entities.playhistoryentry.name at 2. SQLite Error Misuse
  at dwd.core.sqlite.SimpleSQLiteCommand.BindParameter (IntPtr stmt, Int32 index, System.String value) [0x00000] in <filename unknown>:0 
  at dwd.core.sqlite.SimpleSQLiteCommand.AddArgument (System.String arg) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.TryLocalize (System.String key, System.String& value, System.Object[] args) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.Localize (System.String key, System.Object[] args) [0x00000] in <filename unknown>:0 
  at L.LT (System.String key) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.get_DisplayText () [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.ToString () [0x00000] in <filename unknown>:0 
  at DeckTracker.LocalizableTextTokenizer.Tokenize (DeckTracker.DwdModelWalker walker, ICycleDetector detector, System.Collections.Generic.List`1 tokens, System.Object value) [0x00000] in <filename unknown>:0 
dwd.core.sqlite.SQLiteException: Unable to bind parameter com.direwolfdigital.hydra.rules.entities.playhistoryentry.name at 2. SQLite Error Misuse
  at dwd.core.sqlite.SimpleSQLiteCommand.BindParameter (IntPtr stmt, Int32 index, System.String value) [0x00000] in <filename unknown>:0 
  at dwd.core.sqlite.SimpleSQLiteCommand.AddArgument (System.String arg) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.TryLocalize (System.String key, System.String& value, System.Object[] args) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizationDB.Localize (System.String key, System.Object[] args) [0x00000] in <filename unknown>:0 
  at L.LT (System.String key) [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.get_DisplayText () [0x00000] in <filename unknown>:0 
  at dwd.core.localization.LocalizableText.ToString () [0x00000] in <filename unknown>:0 
  at DeckTracker.LocalizableTextTokenizer.Tokenize (DeckTracker.DwdModelWalker walker, ICycleDetector detector, System.Collections.Generic.List`1 tokens, System.Object value) [0x00000] in <filename unknown>:0

**Comment by extesy** [comment] 2017-07-27 12:01
@VitaliyKulikov Please don't create duplicate issues. This ticket is a duplicate of #96.

**Closed by extesy** 2017-07-27 12:01 UTC
