### ISSUE TITLE
Trouble with resizing decks

### ISSUE THREAD

**Issue by B-o-r-r-i** [extesy/DeckTracker#162] opened 2017-12-15 14:30 UTC
Hi, I just downloaded the deck tracker today and I think it's very good but I did run into an issue while trying to decrease the size of my opponents deck size. I first of all had great difficulty in trying to decrease the size but persevered and kept trying. Eventually I was successful but it decreased in size in one swoop to its minimum size. Now I cannot get it to increase in size at all because its so tiny. Maybe you can help me out, thanks.

**Comment by B-o-r-r-i** [comment] 2017-12-15 16:56
Hi, I managed to increase it, but I find it is rather difficult to increase/decrease the size of opponents deck compared to your own/the player for some reason. Thank you.

**Comment by extesy** [comment] 2017-12-18 20:10
Duplicate of #110.

**Closed by extesy** 2017-12-18 20:10 UTC

**Comment by mistermartin1** [comment] 2018-09-17 16:55
It is impossible to resize the Opponent deck.

**Comment by mistermartin1** [comment] 2018-09-17 16:59
It is impossible to resize the Opponent Deck
![20180917135627_1](https://user-images.githubusercontent.com/43350189/45637706-8e8db800-ba81-11e8-9c39-50f8bab3609f.jpg)
