### ISSUE TITLE
Created cards are tracked as being removed from deck

### ISSUE THREAD

**Issue by joshkillinger** [extesy/DeckTracker#68] opened 2017-07-14 04:48 UTC
When a card is created and that card is also in the deck, the remaining card count decreases.

Example:
1. Have Firebolt x3 in the deck.
2. Play Cunning Ally (and have it create a Firebolt).
3. Observe Firebolt count is now x2 when it should still be x3.

**Comment by extesy** [comment] 2017-07-14 04:52
@joshkillinger Try version `1.0.55`. Your issue is a duplicate of #62 which has been fixed.

**Closed by extesy** 2017-07-14 04:52 UTC
