### ISSUE TITLE
No way out

### ISSUE THREAD

**Issue by docteurbug** [extesy/DeckTracker#208] opened 2018-04-19 22:25 UTC
I've both TESL client (Steam one and Bethesda one) and the last version of DeckTracker but it don't work. Game is detecting but nothing appear and nothing can be import !

what can i do ? Thanks

**Comment by extesy** [comment] 2018-04-20 00:21
Duplicate of #5. Make sure you try the solution from FAQ first.

**Closed as completed by extesy** 2018-04-20 00:21 UTC
