### ISSUE TITLE
Tracker shows only 6 cards from deck

### ISSUE THREAD

**Issue by Ptero1989** [extesy/DeckTracker#156] opened 2017-11-29 22:21 UTC
Deck Tracker shows only 6 cards from deck. Any clue how to fix this? https://ibb.co/fNkUkG
Testing on other decks shows that its random. In one i see only 2 cards i other 4,6,7 etc.

**Comment by extesy** [comment] 2017-11-30 00:02
Duplicate of #155

**Closed by extesy** 2017-11-30 00:02 UTC
