### ISSUE TITLE
Deck Tracker rarely recognizes Legends!

### ISSUE THREAD

**Issue by KopisGaming** [extesy/DeckTracker#137] opened 2017-10-05 03:06 UTC
I start up UDT (Deck Tracker) and wait for a few seconds for it to pop-up. Once it does, I start Elder Scrolls Legends and immediately notice (about 80-90% of the time) that UDT has not recognized that TESL has been started. Prior to the new update (both UDT and TESL) I didn't have any problems with the Deck Tracker.

When I updated the Deck Tracker, after the newest version of TESL was released, I only got a new exe file, if it helps. Ask whatever questions you need to, just help me fix this!

**Comment by extesy** [comment] 2017-11-09 00:26
It's essentially a duplicate of #5. Injecting dlls into a game process is not a bulletproof process. I'm adding heuristics here and there to improve reliability but on some machines this problem happens more often than on others.

**Closed by extesy** 2017-11-09 00:26 UTC
Labels: bug, The Elder Scrolls: Legends
