### ISSUE TITLE
Unable to access clipboard

### ISSUE THREAD

**Issue by andyPetsch** [extesy/DeckTracker#207] opened 2018-04-18 20:38 UTC
Hey there!

I installed UDT and opened it. UDT does detect TES:L.
When clicking on "export full collection" I get the message "unable to access clipboard".

I tried running UDT as administrator which did not work.

Any suggestions?
Best, Andy

**Comment by extesy** [comment] 2018-04-19 02:44
Duplicate of #129

**Closed as completed by extesy** 2018-04-19 02:44 UTC
