### ISSUE TITLE
Gray out 'Export Full Collection'

### ISSUE THREAD

**Issue by StrategyKB** [extesy/DeckTracker#76] opened 2017-07-15 12:42 UTC
1. I have installed Universal Deck Tracker v1.0.56
2. Started Elder Scrolls Legends
3. I see 'Running game detected: TheElderScrollsLegends'
4. I go to the Collections page in the game
 Expected behavior: being able to press 'Export Full Collection'
 Actual behavior: the Export Full Collection & Import Deck is grayed out

Thoughts? Am I missing a step?
![decktracker](https://user-images.githubusercontent.com/30004199/28239407-961f277e-6939-11e7-8ba5-612aa441aac5.PNG)

**Comment by extesy** [comment] 2017-07-15 16:16
@StrategyKB Known issue, duplicate of #5.

**Closed by extesy** 2017-07-15 16:16 UTC
