### ISSUE TITLE
Running game detected message is red

### ISSUE THREAD

**Issue by Vampiricangeluk** [extesy/DeckTracker#74] opened 2017-07-14 17:06 UTC
Hi
When I start decktracker it just keeps coming up with the running game detected message at the top but in red so it's not connecting with the game.   Works fine on my husbands computer which is identical to mine. Can you think of anything to try to get it to work please?  we've both looked at can't fix it ARRRGGGG. Many thanks

**Comment by extesy** [comment] 2017-07-14 17:32
Known issue, duplicate of #5.

**Closed by extesy** 2017-07-14 17:32 UTC
