### ISSUE TITLE
Deck tracker launch problem

### ISSUE THREAD

**Issue by Rwendoll** [extesy/DeckTracker#139] opened 2017-10-10 21:34 UTC
Hello

Wanted to start using deck tracker on ESL today and when I follow instructions, lunch UDT with admin priv and then start ESL I Get a Black screen and the game doesn't load, the only info i get is the version of UDT on the bottom right . If I start the game first and then UDT the game launches well with the version info but when i try to use UDT it says "Something went wrong...".
I read all FAQs and installed access runtimes just in case, but no luck.

Can you tell me if I'm doing something wrong I can't figure this out.

Thanks

**Comment by extesy** [comment] 2017-10-10 23:15
This bug is a duplicate of #138. I'm closing this ticket to avoid duplicate reports.

**Closed by extesy** 2017-10-10 23:15 UTC

**Comment by Omenofis** [comment] 2017-10-21 11:52
I have the same problem, there is no answer to it.... who knows perhaps with a new version of game and tracker will be solved automatically...  lol don't worry u are not alone there... few of us share the problem.
